AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The tranmere6 stack
Globals:
  Function:
    Timeout: 3
    AutoPublishAlias: live
Parameters:
  Deployment:
    Type: String
    Default: Canary10Percent5Minutes
  EnvName:
    Type: String
    Default: sit1
    Description: The name of the environment to deploy to
    AllowedValues:
    - local
    - ci1
    - sit1
    - pre1
    - prod1
Mappings:
  SpecialFeature1:
    ci1:
      answer: 1
    sit1:
      answer: 1
    pre1:
      answer: 1
    prod1:
      answer: 1
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: tranmere6
      DefinitionUri: s3://tranmere-web-api/2c80d2075cdd82a5faf14f48e1d97df8
  tranmere6:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://tranmere-web-api/9826eee40843dc30005916ec990c6ca8
      Handler: tranmere6.handler
      Runtime: nodejs12.x
      DeploymentPreference:
        Type:
          Ref: Deployment
        Alarms:
        - Ref: AliasErrorMetricGreaterThanZeroAlarm
        - Ref: LatestVersionErrorMetricGreaterThanZeroAlarm
      Tracing: Active
      Environment:
        Variables:
          EnvironmentName:
            Ref: EnvName
          SpecialFeature:
            Fn::FindInMap:
            - SpecialFeature1
            - Ref: EnvName
            - answer
      Events:
        PageRequest:
          Type: Api
          Properties:
            Path: /
            RestApiId:
              Ref: RestApi
            Method: get
  AliasErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      AlarmActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      OKActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      InsufficientDataActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value:
          Fn::Sub: ${tranmere6}:live
      - Name: FunctionName
        Value:
          Ref: tranmere6
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      AlarmActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      OKActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      InsufficientDataActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value:
          Fn::Sub: ${tranmere6}
      - Name: FunctionName
        Value:
          Ref: tranmere6
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/GET/
      FunctionName:
        Ref: tranmere6
      Principal: apigateway.amazonaws.com
  StagingBasePathMapping:
    DependsOn: RestApiProdStage
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: tranmere6
      DomainName:
        Fn::Sub: api.${EnvName}.tranmere-web.com
      RestApiId:
        Ref: RestApi
      Stage: Prod
Outputs:
  Endpoint:
    Description: API Gateway endpoint URL the endpoint
    Value:
      Fn::Sub: https://api.${EnvName}.tranmere-web.com/tranmere6/
